# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- RestAssured_10.8

pool:
  vmImage: 'ubuntu-latest'

resources:
  - repo: self
    clean: true


steps:
- checkout: self
   clean: true
    persistCredentials: true

    
  
